name: gym
description: "A fitness app equipped with location to show sports and gym arena within the location of a person."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  location:
  geolocator:
  map_launcher:
  google_maps_flutter:
  flutter_map:
  path_provider: ^2.1.2
  path: ^1.9.0
  json_annotation:
  freezed_annotation:
  logger:
  http:
  dio:
  hive_flutter:
  hive:
  fluttertoast:
  provider:
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20


  sqlite3: any
  flutter_spinkit: ^5.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  freezed:
  json_serializable:
  flutter_lints: ^3.0.1
  drift_dev: ^2.15.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


